services:
  app:
    build: .
    container_name: yellowcar-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgres://yellowcar_user:anabelle67@infracore-yellowcardb-f8ftmr:5432/yellowcar_db
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  db:
    image: postgres:15-alpine
    container_name: yellowcar-db
    restart: always
    environment:
      - POSTGRES_USER=yellowcar_user
      - POSTGRES_PASSWORD=anabelle67
      - POSTGRES_DB=yellowcar_db
    volumes:
      - yellowcar-db-data:/var/lib/postgresql/data

volumes:
  yellowcar-db-data:
